### PR TITLE
Identify service accounts utilizing deprecated APIs

### PR DESCRIPTION
**Pull request by tkrishtop**
TestDallasWorkload: preflight-green

### CODE REVIEW

**Comment by tkrishtop** [comment]
recheck

**Comment by tkrishtop** [comment]
retest

**Comment by tkrishtop** [comment]
Tested locally, the new Junit file contains SA using to-be-removed API now: 
```
<?xml version="1.0" ?>
<testsuites disabled="0" errors="0" failures="2" tests="3" time="0.0">
	<testsuite disabled="0" errors="0" failures="2" name="Workload Compatibility with OCP Versions" skipped="0" tests="3" time="0">
		<testcase name="Check compatibility with OCP-4.11" classname="Workload Compatibility with OCP-4.11"/>
		<testcase name="Check compatibility with OCP-4.12" classname="Workload Compatibility with OCP-4.12">
			<failure type="failure" message="Workload uses APIs that are no longer available in OCP-4.12: events.v1beta1.events.k8s.io (service accounts: system:serviceaccount:default:eventtest-operator-service-account), podsecuritypolicies.v1beta1.policy (service accounts: system:kube-controller-manager)"/>
		</testcase>
		<testcase name="Check compatibility with OCP-4.13" classname="Workload Compatibility with OCP-4.13">
			<failure type="failure" message="Workload uses APIs that are no longer available in OCP-4.13: events.v1beta1.events.k8s.io (service accounts: system:serviceaccount:default:eventtest-operator-service-account), podsecuritypolicies.v1beta1.policy (service accounts: system:kube-controller-manager), flowschemas.v1beta1.flowcontrol.apiserver.k8s.io (service accounts: system:serviceaccount:openshift-cluster-version:default), prioritylevelconfigurations.v1beta1.flowcontrol.apiserver.k8s.io (service accounts: system:serviceaccount:openshift-cluster-version:default)"/>
		</testcase>
	</testsuite>
</testsuites>
```

**Review by manurodriguez — APPROVED** [review]
> CheckDallasWorkload: preflight-green

I believe it's `TestDallasWorkload: preflight-green` ? :thinking:

**Comment by tkrishtop** [comment]
> > CheckDallasWorkload: preflight-green
> 
> I believe it's `TestDallasWorkload: preflight-green` ? 🤔

thank you @manurodriguez, I was wondering to use recheck or retest but did not catch this one :D

**Comment by tkrishtop** [comment]
retest

**Comment by tkrishtop** [comment]
> from change #47:
> 
> * SUCCESS https://www.distributed-ci.io/jobs/c29d8b0f-bc71-4d68-b50f-2a059fd1a56b/jobStates

[does not break](https://www.distributed-ci.io/jobs/c29d8b0f-bc71-4d68-b50f-2a059fd1a56b/tests/307409cd-cdf7-4995-8d75-7aa9d107dae1) the existing functionality either, going to merge.

**Pull request merged**
