### PR TITLE
Retry Opcap release download to mitigate GH timeouts

### PR DESCRIPTION
**Pull request by tkrishtop**
TestDallas: ocp-4.13-vanilla tnf-test-cnf tnf-test-cnf:ansible_extravars=test_network_function_version:HEAD

### CODE REVIEW

**Comment by tkrishtop** [comment]
check dallas ocp-4.13-vanilla tnf-test-cnf tnf-test-cnf:ansible_extravars=test_network_function_version:HEAD

**Review by betoredhat — APPROVED** [review]

**Comment by betoredhat** [comment]
LGTM, thanks

**Comment by betoredhat** [comment]
TestDallas: ocp-4.13-vanilla tnf-test-cnf tnf-test-cnf:ansible_extravars=test_network_function_version:HEAD

**Comment by betoredhat** [comment]
check dallas ocp-4.13-vanilla tnf-test-cnf tnf-test-cnf:ansible_extravars=test_network_function_version:HEAD

**Pull request merged**
