### PR TITLE
bugfixes for Agent Based Installer

### PR DESCRIPTION
**Pull request by nocturnalastro**
Cherry picking bug fix from crucible. 

Test-Hints: assisted-abi

### CODE REVIEW

**Comment by nocturnalastro** [comment]
@arjuhe Can you check this for me.

**Review by thekad — DISMISSED** [review]

**Review by fredericlepied — CHANGES_REQUESTED** [review]
Could we make sure the DCI job for assisted-abi works?

**Review by ramperher — COMMENTED** [review]
The job is failing in the task just after the one that has been changed in generate_agent_iso: https://www.distributed-ci.io/jobs/6caac908-d818-4f82-beb8-5a143d1675ae/jobStates?sort=date&task=1fe56a9d-3744-4907-bc09-d773d4ff85d9

I can see this:

```
"level=error msg=failed to write asset (Agent Installer ISO) to disk: cannot generate ISO image due to configuration errors", "level=fatal msg=failed to fetch Agent Installer ISO: failed to fetch dependency of \"Agent Installer ISO\": failed to generate asset \"Agent Installer Artifacts\": cpio: write too long"
```

Don't know if it's related to pullsecrets, I'd relaunch a job to see if it happens again, and if true, then I believe this should be reviewed.

**Comment by nocturnalastro** [comment]
I think I see the issue. `XDG_RUNTIME_DIR: "{{ config_file_path }}"` also needs to change to `XDG_RUNTIME_DIR: "{{ generated_dir }}"`. I guess config_file_path wasn't cleaned up when we tested.

**Comment by nocturnalastro** [comment]
I haven't been able to recreate the issue. However I have a suspicion that is the issue so I'll add a commit to change that an see if that corrects the issue.

**Comment by nocturnalastro** [comment]
Looks like I was right. I'll get that fix merged back into crucible (for while we still haven't converted over to the collection).

**Review by fredericlepied — APPROVED** [review]

**Review by ramperher — APPROVED** [review]
LGTM

**Pull request merged**
