### PR TITLE
Attach multiple product listings during certification

### PR DESCRIPTION
**Pull request by tkrishtop**

### CODE REVIEW

**Comment by tkrishtop** [comment]
check workload multiple-pls

**Comment by tkrishtop** [comment]
check workload multiple-pls

**Comment by tkrishtop** [comment]
check workload multiple-pls

**Comment by tkrishtop** [comment]
check workload multiple-pls

**Comment by tkrishtop** [comment]
check workload multiple-pls

**Comment by tkrishtop** [comment]
check workload multiple-pls

**Comment by tkrishtop** [comment]
check workload multiple-pls

**Comment by tkrishtop** [comment]
check workload multiple-pls

**Comment by tkrishtop** [comment]
check workload multiple-pls

**Comment by tkrishtop** [comment]
check workload multiple-pls

**Comment by tkrishtop** [comment]
check workload multiple-pls

**Comment by tkrishtop** [comment]
check workload multiple-pls

**Comment by tkrishtop** [comment]
check workload multiple-pls

**Comment by tkrishtop** [comment]
check workload multiple-pls

**Comment by tkrishtop** [comment]
check workload multiple-pls

**Comment by tkrishtop** [comment]
check workload multiple-pls

**Comment by tkrishtop** [comment]
check workload multiple-pls

**Comment by tkrishtop** [comment]
check workload multiple-pls

**Comment by tkrishtop** [comment]
The change works for 2 container projects + 2 PLs, ready for review.

image

**Comment by tkrishtop** [comment]
check workload preflight-green

**Review by ansvu — APPROVED** [review]
We tested both openshift-cnf and helmchart and they worked fine. you can merge now. Thanks.
https://www.distributed-ci.io/jobs/ad8241ba-e6b0-4923-9c32-6186ab77dc48/jobStates?sort=date

https://www.distributed-ci.io/jobs/0b20111b-5c8d-45d7-bc65-2b78f8417a90/jobStates?sort=date

**Review by manurodriguez — APPROVED** [review]
LGTM

**Pull request merged**
