### PR TITLE
[DNM] Automate selinux setup for assisted ABI 

### PR DESCRIPTION
**Pull request by tkrishtop**
Test-Hints: assisted-abi

### CODE REVIEW

**Comment by tkrishtop** [comment]
cc: @ramperher

**Comment by tkrishtop** [comment]
The idea is to get help of @nsilla and @pierreblanc to automate the selinux config for the assisted setup.

**Comment by nicomola** [comment]
from change https://github.com/redhatci/ansible-collection-redhatci-ocp/pull/137:
- SUCCESS https://www.distributed-ci.io/jobs/cbeb1b6c-8b61-4c14-bfa8-33d020672f45/jobStates

**Comment by tkrishtop** [comment]
[ABI has passed with permissive selinux](https://www.distributed-ci.io/jobs/ccd59e67-ef37-4f27-8847-373f3805f9c5/jobStates?sort=date). We'll probably stop selinux setup at this point, and move towards upgrade etc.

**Pull request closed without merging**
