### PR TITLE
Retries for installer extract

### PR DESCRIPTION
**Pull request by betoredhat**
Test-Hints: force-check

### CODE REVIEW

**Comment by betoredhat** [comment]
check dallas ocp-4.14-vanilla

**Review by manurodriguez — APPROVED** [review]
LGTM

**Review by thekad — COMMENTED** [review]
This looks good to me, but I'm curious what failure you saw? I think this operation is pretty straightfoward if it fails it will fail always, do you have an example of a fail?

**Comment by betoredhat** [comment]
> This looks good to me, but I'm curious what failure you saw? I think this operation is pretty straightfoward if it fails it will fail always, do you have an example of a fail?

Mainly time outs reaching the registry

https://www.distributed-ci.io/jobs/067511bb-dc2b-46f3-9066-159e7c9f5b9a/jobStates
https://www.distributed-ci.io/jobs/ff332ba2-1a65-4869-a68f-31d40f0de56e/jobStates

**Review by pierreblanc — APPROVED** [review]
LGTM

**Comment by betoredhat** [comment]
Thanks

**Pull request merged**
