### PR TITLE
Define PL on container level

### PR DESCRIPTION
**Pull request by tkrishtop**

### CODE REVIEW

**Comment by tkrishtop** [comment]
check workload multiple-pls

**Comment by ansvu** [comment]
from change https://github.com/redhatci/ansible-collection-redhatci-ocp/pull/207:
- FAILURE https://www.distributed-ci.io/jobs/15dac86a-b825-4314-9485-610bc8bfcbd0/jobStates

**Comment by ansvu** [comment]
from change https://github.com/redhatci/ansible-collection-redhatci-ocp/pull/207:
- FAILURE https://www.distributed-ci.io/jobs/f3022162-f51d-4b72-b1a9-b14904ef7b1f/jobStates

**Comment by tkrishtop** [comment]
check workload multiple-pls

**Comment by tkrishtop** [comment]
check workload multiple-pls

**Comment by tkrishtop** [comment]
check workload multiple-pls

**Comment by tkrishtop** [comment]
check workload multiple-pls

**Comment by tkrishtop** [comment]
check workload multiple-pls

**Comment by tkrishtop** [comment]
check workload multiple-pls

**Comment by tkrishtop** [comment]
check workload multiple-pls

**Comment by tkrishtop** [comment]
check workload multiple-pls

**Comment by tkrishtop** [comment]
check workload multiple-pls

**Comment by tkrishtop** [comment]
check workload multiple-pls

**Comment by tkrishtop** [comment]
The change is working, but I struggle to get 100% green job because of the Pyxis API timeouts.

image

**Review by manurodriguez — APPROVED** [review]
Thanks for all the hard work here!
LGTM

**Pull request merged**
