### PR TITLE
Remove custom virt module

### PR DESCRIPTION
**Pull request by tonyskapunk**
Use community.libvirt instead of custom module
Baremetal deploy role used a custom libvirt module, which was a copy of
an old libvirt module. The current functionality of the community module
is enough to stop using the custom module.

Test-Hints: sno

### CODE REVIEW

**Comment by tonyskapunk** [comment]
check dallas ocp-4.13-vanilla

**Comment by tonyskapunk** [comment]
check dallas ocp-4.13-vanilla

**Comment by tonyskapunk** [comment]
recheck

**Comment by tonyskapunk** [comment]
check dallas ocp-4.14-vanilla

**Review by betoredhat — DISMISSED** [review]
LGTM

**Comment by tonyskapunk** [comment]
The reason of the sanity check failures is because the output of the andible-doc check displays multiple plugins in the same line and not in different lines thus the diff shows as if this change is introducing regressions but it's not

https://github.com/redhatci/ansible-collection-redhatci-ocp/actions/runs/7400091481?pr=14

**Review by pierreblanc — DISMISSED** [review]
LVGTM

**Review by fredericlepied — APPROVED** [review]

**Review by fredericlepied — APPROVED** [review]

**Pull request merged**
