### PR TITLE
Create a preflight component when building from the source

### PR DESCRIPTION
**Pull request by tkrishtop**
build-depends: https://github.com/redhat-openshift-ecosystem/openshift-preflight/pull/1111

### CODE REVIEW

**Comment by tkrishtop** [comment]
check workload preflight-green

**Review by ramperher — APPROVED** [review]
LGTM

**Comment by tkrishtop** [comment]
check workload preflight-green

**Comment by tkrishtop** [comment]
I tested using preflight dependency, and the component [was created fine](https://www.distributed-ci.io/topics/afbb1c48-277e-4ddb-aa14-d24fe27434a7/components/132693fe-8cd4-400a-82a3-e4900acc633d ).

I'm going to merge PR now to get the component displayed in the Telco dashboard during the dailies.
The ansible-lint request to change the variable names will be addressed in a separate PR, to thoroughly check all the dependencies:
```
## Regressions from main branch:
-ERROR: roles/preflight/tasks/main.yml:53: var-naming[no-role-prefix]: Variables names from within roles should use include_components_ as a prefix. (vars: gits_list)
```

**Pull request merged**
