### PR TITLE
Fix sanity issues for deprecated-api role

### PR DESCRIPTION
**Pull request by tkrishtop**

### CODE REVIEW

**Comment by tkrishtop** [comment]
check dallas ocp-4.7-vanilla example-cnf

**Comment by tkrishtop** [comment]
check dallas ocp-4.12-vanilla example-cnf

**Comment by tkrishtop** [comment]
check dallas ocp-4.12-vanilla example-cnf

**Comment by tkrishtop** [comment]
check workload preflight-green

**Comment by tkrishtop** [comment]
hi @tonyskapunk could I please ask you for a review?

**Review by ramperher — APPROVED** [review]
LGTM

**Pull request merged**
