### PR TITLE
sin /

### PR DESCRIPTION
**Pull request by svelis1088**
TestBos2: assisted-abi

### CODE REVIEW

**Comment by ramperher** [comment]
Hi @svelis1088 , thanks for your first contribution to redhatci.ocp collection!
From my side, the change looks good, I've verified there are no other parts of the code where this change may impact:

```
$ grep -r extract_dest_path
roles/extract_openshift_installer/defaults/main.yml:extract_dest_path: /tmp/wip/extract/
roles/extract_openshift_installer/defaults/main.yml:pull_secret_file: "{{ extract_dest_path }}/pull_secret.txt"
roles/extract_openshift_installer/defaults/main.yml:openshift_installer_path: "{{ extract_dest_path }}/openshift-install"
roles/extract_openshift_installer/tasks/main.yml:- name: "Create {{ extract_dest_path }}"
roles/extract_openshift_installer/tasks/main.yml:    path: "{{ extract_dest_path }}"
roles/extract_openshift_installer/tasks/main.yml:      --to={{ extract_dest_path }}
```

Just to improve a little bit the PR, could you do the following?

- Change PR title and description to describe what's the role that is changing, what's the purpose of the change, etc.
- Add `TestBos2: abi` in the PR description, so that we'll be able to test a scenario with your change.

Waiting for your review, thanks!

**Comment by fredericlepied** [comment]
retest

**Comment by manurodriguez** [comment]
retest

**Comment by manurodriguez** [comment]
retest

**Comment by ramperher** [comment]
I think this change needs to update the title and PR description for better traceability when merging it.

**Comment by fredericlepied** [comment]
ping @svelis1088

**Pull request closed without merging**
