### PR TITLE
Assisted | Add support to NATted networks

### PR DESCRIPTION
**Pull request by ramperher**
Just retaking the change from https://github.com/redhat-partner-solutions/crucible/pull/257 to include it in the collections

Test-Hints: assisted-abi

### CODE REVIEW

**Comment by ramperher** [comment]
CC @nocturnalastro , if you remember, I started this work in this PR: https://github.com/redhat-partner-solutions/crucible/pull/257, now I'll move it to the collections instead, since it's easier for us to test and troubleshoot

**Comment by nicomola** [comment]
- ERROR https://www.distributed-ci.io/jobs/93ba48c6-0af7-4c3f-912b-be6a7fa7c20c/jobStates
 from https://github.com/redhatci/ansible-collection-redhatci-ocp/pull/92

**Comment by nicomola** [comment]
- ERROR https://www.distributed-ci.io/jobs/6de8b1f7-d906-4b49-a6c9-bd312fe45149/jobStates
 from https://github.com/redhatci/ansible-collection-redhatci-ocp/pull/92

**Comment by nicomola** [comment]
- ERROR https://www.distributed-ci.io/jobs/946d55b6-e7c6-4ae9-a603-eb152cdb5e00/jobStates
 from https://github.com/redhatci/ansible-collection-redhatci-ocp/pull/92

**Comment by nicomola** [comment]
- FAILURE https://www.distributed-ci.io/jobs/d3f9ec06-6255-4fbb-b30e-1525290f0f60/jobStates
 from https://github.com/redhatci/ansible-collection-redhatci-ocp/pull/92

**Comment by nicomola** [comment]
- FAILURE https://www.distributed-ci.io/jobs/e0078c3e-e828-4619-b6ac-446904591bcb/jobStates
 from https://github.com/redhatci/ansible-collection-redhatci-ocp/pull/92

**Comment by nicomola** [comment]
- FAILURE https://www.distributed-ci.io/jobs/3ea21c59-b03f-4cad-afee-9cd42e55fe27/jobStates
 from https://github.com/redhatci/ansible-collection-redhatci-ocp/pull/92

**Comment by nicomola** [comment]
- ERROR https://www.distributed-ci.io/jobs/3c6d0678-9897-4264-bc92-8045170e23eb/jobStates
 from https://github.com/redhatci/ansible-collection-redhatci-ocp/pull/92

**Comment by nicomola** [comment]
- ERROR https://www.distributed-ci.io/jobs/8bb41e71-039d-43be-acab-92f9ec387e2b/jobStates
 from https://github.com/redhatci/ansible-collection-redhatci-ocp/pull/92

**Comment by nicomola** [comment]
- ERROR https://www.distributed-ci.io/jobs/85595b8c-5e75-4ebe-a8ce-80dd84c743ca/jobStates
 from https://github.com/redhatci/ansible-collection-redhatci-ocp/pull/92

**Comment by nicomola** [comment]
- FAILURE https://www.distributed-ci.io/jobs/71f2a9a4-e449-483d-95e4-3ec38c514604/jobStates
 from https://github.com/redhatci/ansible-collection-redhatci-ocp/pull/92

**Comment by nicomola** [comment]
- ERROR https://www.distributed-ci.io/jobs/19826eab-f93f-4773-b483-835b6a45b4e0/jobStates
 from https://github.com/redhatci/ansible-collection-redhatci-ocp/pull/92

**Comment by nicomola** [comment]
- FAILURE https://www.distributed-ci.io/jobs/f0a003ff-c1f9-429d-8f05-44111e71c73d/jobStates
 from https://github.com/redhatci/ansible-collection-redhatci-ocp/pull/92

**Comment by nicomola** [comment]
- ERROR https://www.distributed-ci.io/jobs/61840104-f6dc-4a80-9676-4c55ecc169eb/jobStates
 from https://github.com/redhatci/ansible-collection-redhatci-ocp/pull/92

**Comment by nicomola** [comment]
- FAILURE https://www.distributed-ci.io/jobs/6c932018-d96d-4adb-99f4-2daa83f77ef9/jobStates
 from https://github.com/redhatci/ansible-collection-redhatci-ocp/pull/92

**Comment by nicomola** [comment]
- FAILURE https://www.distributed-ci.io/jobs/bd22a204-073c-4ad5-a6a6-a711c20f2645/jobStates
 from https://github.com/redhatci/ansible-collection-redhatci-ocp/pull/92

**Comment by nicomola** [comment]
- FAILURE https://www.distributed-ci.io/jobs/d0dee0d2-3177-43c6-9458-2296fc148c9c/jobStates
 from https://github.com/redhatci/ansible-collection-redhatci-ocp/pull/92

**Comment by nicomola** [comment]
- FAILURE https://www.distributed-ci.io/jobs/913ea77c-f6f8-4b10-959b-90b450429f42/jobStates
 from https://github.com/redhatci/ansible-collection-redhatci-ocp/pull/92

**Comment by thekad** [comment]
This last run looks good @ramperher can you rebase vs main? Also cc @redhatci/crucible

**Comment by ramperher** [comment]
> This last run looks good @ramperher can you rebase vs main? Also cc @redhatci/crucible

Although the BOS2 test is passing, we still need to validate this change with the partner we're working with. We'll keep updating this change consequently. When it's ready for review, we'll remove the [WIP] tag and rebase the branch accordingly.

**Comment by ramperher** [comment]
I'm creating these two changes to move some of the logic we have tested here in separated changes, now that we know they're working: https://github.com/redhatci/ansible-collection-redhatci-ocp/pull/114 and https://github.com/redhatci/ansible-collection-redhatci-ocp/pull/115

**Comment by nicomola** [comment]
- ERROR https://www.distributed-ci.io/jobs/fffa43bd-ed37-4f95-a9a9-bef9feaf84b6/jobStates
 from https://github.com/redhatci/ansible-collection-redhatci-ocp/pull/92

**Comment by nicomola** [comment]
- ERROR https://www.distributed-ci.io/jobs/ea0636ff-a585-4ad5-af6e-92d690156213/jobStates
 from https://github.com/redhatci/ansible-collection-redhatci-ocp/pull/92

**Comment by nicomola** [comment]
- FAILURE https://www.distributed-ci.io/jobs/d1fb90a8-75cf-422c-ac45-b42664287952/jobStates
 from https://github.com/redhatci/ansible-collection-redhatci-ocp/pull/92

**Comment by nicomola** [comment]
- FAILURE https://www.distributed-ci.io/jobs/f73d4d40-2ed6-4627-8751-6d654b730176/jobStates
 from https://github.com/redhatci/ansible-collection-redhatci-ocp/pull/92

**Comment by nicomola** [comment]
- FAILURE https://www.distributed-ci.io/jobs/2d5d957d-4ec7-4e5d-9879-ed13b425f196/jobStates
 from https://github.com/redhatci/ansible-collection-redhatci-ocp/pull/92

**Comment by nicomola** [comment]
- FAILURE https://www.distributed-ci.io/jobs/5f60ee3e-1eb4-44c2-8078-5e0eb0fbc333/jobStates
 from https://github.com/redhatci/ansible-collection-redhatci-ocp/pull/92

**Comment by nicomola** [comment]
- FAILURE https://www.distributed-ci.io/jobs/b7e7a76e-6208-46ee-a8d4-32c5ec3dba21/jobStates
 from https://github.com/redhatci/ansible-collection-redhatci-ocp/pull/92

**Comment by nicomola** [comment]
- SUCCESS https://www.distributed-ci.io/jobs/5caa6ee5-8a48-49bb-8f6c-2d0b74bbef22/jobStates
 from https://github.com/redhatci/ansible-collection-redhatci-ocp/pull/92

**Review by tkrishtop — APPROVED** [review]
Tested green: https://www.distributed-ci.io/jobs/5caa6ee5-8a48-49bb-8f6c-2d0b74bbef22/jobStates?sort=date 

The SELinux fixes and automation will go into a separate PR

**Comment by nicomola** [comment]
- SUCCESS https://www.distributed-ci.io/jobs/0cc00a61-629d-4aa9-add8-9217a2e17121/jobStates
 from https://github.com/redhatci/ansible-collection-redhatci-ocp/pull/92

**Review by nocturnalastro — APPROVED** [review]

**Comment by nocturnalastro** [comment]
@ramperher Probably a good idea to squash your commits before the merge :)

**Comment by ramperher** [comment]
> @ramperher Probably a good idea to squash your commits before the merge :)

@nocturnalastro is it fine to leave the story as it is right now? since there are two contributors to this PR, maybe squashing the commits may disturb the story of this change. Also, the commits will be squashed for sure when merging. Here's an example: https://github.com/redhatci/ansible-collection-redhatci-ocp/commit/b2a4b70fef9a7b38c40551c7cd6b11a6f4ef8e59

**Pull request merged**
