### PR TITLE
Increase CNF certsuite to use v5.1.2

### PR DESCRIPTION
**Pull request by tonyskapunk**
Newest release is [v5.1.2](https://github.com/test-network-function/cnf-certification-test/releases/tag/v5.1.2)

---

- [x] tnf-test-cnf-green (default) - https://www.distributed-ci.io/jobs/6b9c4f2a-1c24-4c25-83cb-fbb2ececaa25
- [x] tnf-test-cnf - https://www.distributed-ci.io/jobs/22b8d329-e61d-4d89-b6e6-fe4f8e704173/jobStates

---

Test-hint: no-check

### CODE REVIEW

**Comment by tonyskapunk** [comment]
retest

**Comment by tonyskapunk** [comment]
retest

**Comment by tonyskapunk** [comment]
retest

**Review by manurodriguez — APPROVED** [review]
LGTM

**Pull request merged**
