### PR TITLE
Switch to kubernetes.core collection

### PR DESCRIPTION
**Pull request by tonyskapunk**
The kubernetes.core is the new name of the community.kubernetes ansible collection. community.kubernetes has been deprecated.

### CODE REVIEW

**Comment by tonyskapunk** [comment]
[Failed task due to dependency](https://www.distributed-ci.io/jobs/3fad771a-b7c2-4556-ab9f-e3b6edc49775/jobStates?sort=date&task=a66442a8-59d6-4de2-b673-e7942a2c7b9f)

```Shell
task path: /home/dciteam/github/ansible-collection-redhatci-ocp-pr214-f98402886fdf982349374f2a2ea1edcb/collections/ansible_collections/redhatci/ocp/roles/catalog_source/tasks/main.yml:14
fatal: [jumphost]: FAILED! => {"changed": false, "msg": "kubernetes >= 12.0.0 is required"}
```

The challenge is that `python-kubernetes` it's provided through EPEL:

```shell
$ sudo dnf list python3-kubernetes --showduplicates |head
Updating Subscription Management repositories.
Last metadata expiration check: 0:31:20 ago on Fri 15 Mar 2024 06:00:07 PM CDT.
Installed Packages
python3-kubernetes.noarch                  1:11.0.0-6.el8                  @epel
Available Packages
python3-kubernetes.noarch                  1:11.0.0-6.el8                  epel 
```

And the latest version is 11.0: https://src.fedoraproject.org/rpms/python-kubernetes

**Comment by fredericlepied** [comment]
> ```shell
> kubernetes >= 12.0.0 is required
> ```

ok I requested to create our own python-kubernetes package in https://softwarefactory-project.io/r/c/config/+/31126

**Comment by tonyskapunk** [comment]
> * ad43f916-be93-4f41-a7ec-bf8e95c6df60/jobStates

This error is expected as is a run in the app-agent with TNF and the test does not install python libraries. But the change will be validated with libvirt (IPI) (dci-openshift-agent) and the control plane example (dci-openshift-app-agent)

**Comment by tonyskapunk** [comment]
I was not expecting this issue, the logs show the right kubernetes python lib was installed:

```Shell
+ pip install -U -I -r ansible-collection-redhatci-ocp/requirements.txt
Collecting kubernetes==25.3.0
  Using cached kubernetes-25.3.0-py2.py3-none-any.whl (1.4 MB)
Collecting requests
  Using cached requests-2.27.1-py2.py3-none-any.whl (63 kB)
Collecting requests-oauthlib
  Downloading requests_oauthlib-2.0.0-py2.py3-none-any.whl (24 kB)
Collecting certifi>=14.05.14
  Using cached certifi-2024.2.2-py3-none-any.whl (163 kB)
Collecting python-dateutil>=2.5.3
  Using cached python_dateutil-2.9.0.post0-py2.py3-none-any.whl (229 kB)
Collecting google-auth>=1.0.1
  Using cached google_auth-2.22.0-py2.py3-none-any.whl (181 kB)
Collecting websocket-client!=0.40.0,!=0.41.*,!=0.42.*,>=0.32.0
  Using cached websocket_client-1.3.1-py3-none-any.whl (54 kB)
Collecting six>=1.9.0
  Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
Collecting urllib3>=1.24.2
  Using cached urllib3-1.26.18-py2.py3-none-any.whl (143 kB)
Collecting setuptools>=21.0.0
  Using cached setuptools-59.6.0-py3-none-any.whl (952 kB)
Collecting pyyaml>=5.4.1
  Using cached PyYAML-6.0.1-cp36-cp36m-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (677 kB)
Collecting pyasn1-modules>=0.2.1
  Using cached pyasn1_modules-0.3.0-py2.py3-none-any.whl (181 kB)
Collecting cachetools<6.0,>=2.0.0
  Using cached cachetools-4.2.4-py3-none-any.whl (10 kB)
Collecting rsa<5,>=3.1.4
  Using cached rsa-4.9-py3-none-any.whl (34 kB)
Collecting idna<4,>=2.5
  Using cached idna-3.6-py3-none-any.whl (61 kB)
Collecting charset-normalizer~=2.0.0
  Using cached charset_normalizer-2.0.12-py3-none-any.whl (39 kB)
Collecting oauthlib>=3.0.0
  Using cached oauthlib-3.2.2-py3-none-any.whl (151 kB)
Collecting pyasn1<0.6.0,>=0.4.6
  Using cached pyasn1-0.5.1-py2.py3-none-any.whl (84 kB)
Installing collected packages: urllib3, pyasn1, idna, charset-normalizer, certifi, six, rsa, requests, pyasn1-modules, oauthlib, cachetools, websocket-client, setuptools, requests-oauthlib, pyyaml, python-dateutil, google-auth, kubernetes
Successfully installed cachetools-4.2.4 certifi-2024.2.2 charset-normalizer-2.0.12 google-auth-2.22.0 idna-3.6 kubernetes-25.3.0 oauthlib-3.2.2 pyasn1-0.5.1 pyasn1-modules-0.3.0 python-dateutil-2.9.0.post0 pyyaml-6.0.1 requests-2.27.1 requests-oauthlib-2.0.0 rsa-4.9 setuptools-59.6.0 six-1.16.0 urllib3-1.26.18 websocket-client-1.3.1
```

But after the installation a failure was found as the task was not able to use the virtualenv set in the test

```Shell
TASK [redhatci.ocp.oc_setup : Set htpasswd config secret in openshift] *********
task path: /var/lib/dci-openshift-agent/github/ansible-collection-redhatci-ocp-pr214-62107c45b693ca38948675dd589efe18/collections/ansible_collections/redhatci/ocp/roles/oc_setup/tasks/main.yml:40
fatal: [localhost]: FAILED! => {"changed": false, "msg": "kubernetes >= 12.0.0 is required"}
```

I'm running a test from https://softwarefactory-project.io/r/c/dci-openshift-agent/+/31071 because those changes were not pulled in here.

**Pull request closed without merging**
