### PR TITLE
Enable Preflight debugging for multi-operators certification

### PR DESCRIPTION
**Pull request by tkrishtop**
Re-enable debugging for massive certification with dozens of operators and multiple images per operator.

### CODE REVIEW

**Comment by tkrishtop** [comment]
check workload preflight-green

**Comment by tkrishtop** [comment]
check workload preflight-green

**Comment by manurodriguez** [comment]
Last job might have failed because I impacted worker-2 during another test, now it's back, so testing again:

check workload preflight-green

**Review by manurodriguez — APPROVED** [review]
LGTM

**Pull request merged**
