### PR TITLE
No log for extra verbose tasks

### PR DESCRIPTION
**Pull request by betoredhat**
##### SUMMARY

Logging produced by these tasks may break the DCI GUI.

##### ISSUE TYPE

- Bug, Docs Fix, or other nominal change

##### Tests

- [x] TestBos2: acm-hub -  https://www.distributed-ci.io/jobs/a527c9fb-452e-49aa-a67b-d437a7652c56/jobStates

---

Test-Hints: no-check

### CODE REVIEW

**Review by manurodriguez — APPROVED** [review]
LGTM

**Review by tkrishtop — APPROVED** [review]
LGTM, let's merge

**Review by thekad — APPROVED** [review]
:sheep:  it

**Comment by tonyskapunk** [comment]
retest

**Pull request merged**
