### PR TITLE
Fix typos in READMEs

### PR DESCRIPTION
**Pull request by tonyskapunk**
Fixing cases, typos and proper nouns.

Test-Hints: no-check

### CODE REVIEW

**Review by pierreblanc — APPROVED** [review]
LVGTM

**Review by tkrishtop — CHANGES_REQUESTED** [review]
LGTM, except for the `Life-cycle`, it's better to use the official version [Operator Lifecycle Manager](https://docs.openshift.com/container-platform/4.15/operators/understanding/olm/olm-understanding-olm.html)

**Review by tkrishtop — APPROVED** [review]
LGTM, thank you @tonyskapunk

**Review by thekad — APPROVED** [review]
:memo:

**Pull request merged**
