### PR TITLE
Retry clonning repo

### PR DESCRIPTION
**Pull request by betoredhat**

### CODE REVIEW

**Comment by betoredhat** [comment]
check dallas ocp-4-13-vanilla tnf-test-cnf

**Comment by betoredhat** [comment]
check dallas ocp-4.13-vanilla tnf-test-cnf

**Review by ramperher — APPROVED** [review]
LGTM

**Review by tkrishtop — APPROVED** [review]
LGTM thanks Beto

**Review by capolrik — APPROVED** [review]

**Review by thekad — APPROVED** [review]
LGTM

**Pull request merged**
