### PR TITLE
Notify on publish errors

### PR DESCRIPTION
**Pull request by tonyskapunk**
Submit a notification message to slack whenever there's an issue with publishing the collection into galaxy

Here an example on how the message is crafted:
image

Test-Hints: no-check

### CODE REVIEW

**Review by betoredhat — APPROVED** [review]
Nice, LGTM

**Comment by thekad** [comment]
where are these alerts going? #forum-redhatci ? has this webhook been tested?

**Comment by tonyskapunk** [comment]
> where are these alerts going? #forum-redhatci ?

Nowhere yet, but I think #forum-redhatci is the best place, unless there's reasons to send them to a diff place

> has this webhook been tested?

Yes, against a different chan, I included the screenshot of it.

**Comment by thekad** [comment]
> > where are these alerts going? #forum-redhatci ?
> 
> Nowhere yet, but I think #forum-redhatci is the best place, unless there's reasons to send them to a diff place
> 
> > has this webhook been tested?
> 
> Yes, against a different chan, I included the screenshot of it.

OK yeah I didn't see it in #forum-redhatci that's why I was asking. LGTM

**Review by thekad — APPROVED** [review]

**Pull request merged**
