### PR TITLE
fbc catalog - Use default channel

### PR DESCRIPTION
**Pull request by betoredhat**
##### SUMMARY
Use the default bundle channel

##### ISSUE TYPE

- Bug

##### Tests

- [] TestDallas - <JobID>

TestDallas: ocp-4.16-vanilla

### CODE REVIEW

**Comment by betoredhat** [comment]
Currently, the fbc_catalog is only used when testing upstream catalogs, which are no longer active. This change has been validated in the pre-ga automation.

**Review by ramperher — COMMENTED** [review]
Do you have a job where this is validated in pre-ga automation? Because in the last passed job, I cannot see this modified task being executed.

**Comment by betoredhat** [comment]
> Do you have a job where this is validated in pre-ga automation? Because in the last passed job, I cannot see this modified task being executed.

Thanks, Ramon. Yes, I have one. Unfortunately, it is an internal site that not all the team can access.

**Review by tonyskapunk — APPROVED** [review]
LGTM

**Pull request merged**
