### PR TITLE
Refactor project creation to WA Pyxis timeout

### PR DESCRIPTION
**Pull request by tkrishtop**
build-depends: https://github.com/dci-labs/dallas-pipelines/pull/1030

### CODE REVIEW

**Comment by tkrishtop** [comment]
check workload multiple-pls

**Comment by tkrishtop** [comment]
check workload multiple-pls

**Comment by tkrishtop** [comment]
check workload multiple-pls

**Comment by tkrishtop** [comment]
check workload multiple-pls

**Comment by tkrishtop** [comment]
check workload multiple-pls

**Comment by ansvu** [comment]
from change https://github.com/redhatci/ansible-collection-redhatci-ocp/pull/213:
- FAILURE https://www.distributed-ci.io/jobs/d314e9a6-4654-49c9-9877-b98c39b51188/jobStates

**Comment by tkrishtop** [comment]
[Tested green](https://www.distributed-ci.io/jobs/34a7498b-a734-4fa2-ae53-5321606e0750/jobStates) in Dallas, now testing in Andrew's lab.

**Comment by ansvu** [comment]
from change https://github.com/redhatci/ansible-collection-redhatci-ocp/pull/213:
- FAILURE https://www.distributed-ci.io/jobs/c6cbcd5d-067b-4183-aa2b-e1c6eb25150f/jobStates

**Comment by ansvu** [comment]
from change https://github.com/redhatci/ansible-collection-redhatci-ocp/pull/213:
- SUCCESS https://www.distributed-ci.io/jobs/c443bd77-64bf-4ee5-962d-fa3c1805aaf9/jobStates

**Review by ansvu — APPROVED** [review]
Tested with two PLs on container project and one PL on other second test. Timeout on PL task is longer an issue and it worked fine now.
https://www.distributed-ci.io/jobs/c443bd77-64bf-4ee5-962d-fa3c1805aaf9

**Review by manurodriguez — APPROVED** [review]
LGTM

**Pull request merged**
