### PR TITLE
Microshift customization

### PR DESCRIPTION
**Pull request by thekad**
Tackling both DCI-741 and DCI-742 plus a few ansible lint fixes

Test-Hints: no-check

### CODE REVIEW

**Comment by thekad** [comment]
@guillaumevincent can you make your agent PR depend on this one so we can test it?

**Comment by thekad** [comment]
Here's a job with customization in place https://www.distributed-ci.io/jobs/6c3fc21a-456c-4729-84b5-e19a8604e709/jobStates?sort=date

1. Added an extra repo (DCI repo) as a blueprint to the installer successfully (still figuring out how to properly test this)
2. Added a small %post script to the kickstart to create a file (/opt/kickstart.txt) and verified in the test-sut hook it exists
3. Added ability to furter customize the final installer compose, also need to figure out how to test this

**Comment by thekad** [comment]
OK I have a job that tests all the pieces here https://www.distributed-ci.io/jobs/40fd9995-33d7-46f2-9c7c-2a9d547f67fd/jobStates?sort=date

I am using the following pipeline definition:

```yaml
---
- name: Microshift
  stage: install
  ansible_cfg: /var/lib/dci-openshift-agent/app/local.cfg
  ansible_playbook: /var/lib/dci-openshift-agent/tmp/dci-openshift-agent/plays/microshift/main.yml
  dci_credentials: /etc/dci-pipeline/credentials.yml
  topic: OCP-4.14
  components:
    - repo?name:Microshift 4.14.0 rc.7
  ansible_extravars:
    hooks_dir: /var/lib/dci-openshift-agent/app/microshift-hooks
    cluster: microshift
    rhsm_offline_token: <REDACTED>
    rhsm_org_id: <REDACTED>
    rhsm_activation_key: <REDACTED>
    sushy_tools_bmc_address: "localhost:8082"
    microshift_generate_iso_ks_post_commands:
      - echo OK > /opt/kickstart.txt
    microshift_generate_iso_additional_blueprints:
      dci:
        url: https://packages.distributed-ci.io/repos/current/el/9/x86_64/
    microshift_generate_iso_customization_fragment: |
      [[packages]]
      name = "dci-release"
    suts:
      - name: "sut1"
        memory: 4096
        vcpu: 2
        disk_size: 20

```

And this is my test-sut hook:

```yaml
- name: test_ Check if kickstart file exists
  ansible.builtin.stat:
    path: /opt/kickstart.txt
  register: st

- name: test_ Assert kickstart file exists
  ansible.builtin.assert:
    that: "st.stat.exists | bool"

- name: test_ Check if dci-release package was installed
  ansible.builtin.command: "rpmquery dci-release"
  register: rpmq

- name: test_ Assert dci-release was installed
  ansible.builtin.assert:
    that: "rpmq.rc == 0"
```

You can tell all features present in this PR are being tested: extra kickstart commands, additional blueprints and compose customization.

**Review by fdaencarrh — COMMENTED** [review]
LGTM

**Review by fdaencarrh — APPROVED** [review]
lgtm

**Comment by thekad** [comment]
recheck

**Pull request merged**
