### PR TITLE
Prefer podman for ansible tests

### PR DESCRIPTION
**Pull request by tonyskapunk**
Test-Hints: no-check

### CODE REVIEW

**Comment by tonyskapunk** [comment]
retest

**Comment by tonyskapunk** [comment]
recheck

**Review by thekad — DISMISSED** [review]
LGTM had questions re: apt-get download vs install, clarified in chat

**Comment by tonyskapunk** [comment]
recheck

**Comment by tonyskapunk** [comment]
The current failure is due to the output of the sanity test, I'm able to reproduce it sometimes locally:

`ERROR: plugins/modules/nmcli.py: parameter-type-not-in-doc: Argument 'updelay' in argument_spec defines type as 'sSee documentation for help: https://docs.ansible.com/ansible/devel/dev_guide/testing/sanity/validate-modules.html`


```Shell
## 3.6
❯ ansible-test sanity  --exclude hack/ --verbose --docker --python 3.6 --color --coverage --failure-ok 2>&1 | grep -c sS
0
❯ ansible-test sanity  --exclude hack/ --verbose --docker --python 3.6 --color --coverage --failure-ok 2>&1 | grep -c sS
1

## 3.8
❯ ansible-test sanity  --exclude hack/ --verbose --docker --python 3.8 --color --coverage --failure-ok 2>&1 | grep -c sS
1
❯ ansible-test sanity  --exclude hack/ --verbose --docker --python 3.8 --color --coverage --failure-ok 2>&1 | grep -c sS
0
```

**Review by thekad — APPROVED** [review]

**Pull request merged**
