### PR TITLE
Preflight 1.8.0 checking disconnected annotations for operators

### PR DESCRIPTION
**Pull request by tkrishtop**

### CODE REVIEW

**Comment by tkrishtop** [comment]
check workload preflight-green

**Comment by tkrishtop** [comment]
check workload preflight-green

**Comment by tkrishtop** [comment]
check workload preflight-green

**Comment by tkrishtop** [comment]
check workload preflight-green

**Review by nsilla — APPROVED** [review]
lgtm

**Comment by tkrishtop** [comment]
@ylamgarchal or @thekad could you please approve the PR from the DCI team?

**Review by pierreblanc — APPROVED** [review]
lgtm

**Comment by tonyskapunk** [comment]
> check workload preflight-green

This is triggered automatically when detecting changes in preflight :smile_cat: 

https://github.com/dci-labs/dallas-pipelines/blob/7eab7e9646222b06a1e637d85054225038df7439/bin/github-stream#L174-L177

**Comment by tkrishtop** [comment]
> > check workload preflight-green
> 
> This is triggered automatically when detecting changes in preflight 😸
> 
> https://github.com/dci-labs/dallas-pipelines/blob/7eab7e9646222b06a1e637d85054225038df7439/bin/github-stream#L174-L177

I think, `"$repo" = openshift-preflight` will only work when we have preflight code in the deps (as in the last test here). Just changing the preflight role is currently not enough to trigger the preflight job.

**Comment by tkrishtop** [comment]
recheck

**Pull request merged**
